use_frameworks!

target 'ctble_ios_Example' do
  pod 'ctble_ios', :path => '../'

  target 'ctble_ios_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
