source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/nfnty_admin/conneqtech-specs.git'
use_frameworks!

target 'ctble_Example' do
  pod 'ctble', :path => '../'

  target 'ctble_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
